---
- hosts: all
  sudo: true
  vars:
    web_server: apachephp
    servername: 10.10.10.18
    timezone: Europe/Madrid

  vars_files:
    - vars/common.yml
    - [ "vars/apachephp.yml", "vars/ws_defaults.yml" ]

  roles:
    - init
    - apache
    - php5
    - composer
    - php-pecl
    - app
