---
# application tasks to be customized and to run after the main provision


- shell: cp /vagrant/src/config/parameters.ini.dist /vagrant/src/config/parameters.ini

- name: Install Composer Dependencies
  sudo: false
  composer: working_dir=/vagrant